services:
  airflow:
    build: 
      context: .
      dockerfile: Dockerfile
    image: manoel/airflow:0.0.1
    hostname: airflow
    container_name: airflow
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: False
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: 4QckKjQaadwD3wlADxAFyPgn4W9xs3UmWoMn_VcT6HI=
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./jobs:/opt/airflow/jobs
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com &&
      airflow standalone
      "
  
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:4
    container_name: localstack
    ports:
      - "4566:4566"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      SCREENSHOT_MODE: false 
      xpack.security.enabled: false
    ports:
      - "9200:9200"
      
  elasticsearch-setup:
    image: curlimages/curl:latest
    container_name: elasticsearch_setup
    depends_on:
      - elasticsearch
    volumes:
      - ./setup_elasticsearch.sh:/setup_elasticsearch.sh
    entrypoint: ["/bin/sh", "/setup_elasticsearch.sh"]

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.1
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
volumes:
  postgres_data:
    driver: local